trigger:
- main

pool:
  name: epicbook-deploy-agent

variables:
  TF_IN_AUTOMATION: true


stages:
- stage: Infra
  displayName: "Terraform Infrastructure"
  jobs:
  - job: TerraformJob
    displayName: "Provision Azure Resources"
    steps:

    # ----------------------------
    # SET WORKING DIRECTORY ONCE
    # ----------------------------
    - script: |
        echo "Terraform directory:"
        ls -la
      workingDirectory: $(System.DefaultWorkingDirectory)/infra-epicbook
      displayName: "Debug Directory"

    # ----------------------------
    # 1. GENERATE TFVARS
    # ----------------------------

    - task: DownloadSecureFile@1
      name: sshkey
      displayName: "Download SSH Public Key"
      inputs:
        secureFile: azure_vm_key.pub

    - script: |
        set -e
        KEY_PATH="$(sshkey.secureFilePath)"
        echo "Using key file: $KEY_PATH"
        if [ ! -f "$KEY_PATH" ]; then
          echo "ERROR: SSH key file is missing or empty"
        exit 1
        fi
        SSH_KEY=$(cat "$KEY_PATH")
        if [ -z "$SSH_KEY" ]; then
          echo "ERROR: SSH key is empty"
          exit 1
        fi
        printf 'ssh_public_key="%s"\n' "$SSH_KEY" > pipeline.tfvars
        echo "Generated tfvars:"
        cat pipeline.tfvars
      displayName: "Generate tfvars"
      workingDirectory: $(System.DefaultWorkingDirectory)/infra-epicbook

    # ----------------------------
    # 2. TERRAFORM INIT
    # ----------------------------
    - script: |
        terraform init -reconfigure

      workingDirectory: $(System.DefaultWorkingDirectory)/infra-epicbook
      displayName: "Terraform Init"

    # ----------------------------
    # 3. TERRAFORM PLAN
    # ----------------------------
    - script: |
        set -e
        terraform plan -var-file=pipeline.tfvars -detailed-exitcode
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 1 ]; then
          echo "Terraform plan failed"
          exit 1
        elif [ $EXIT_CODE -eq 2 ]; then
          echo "Terraform plan succeeded with changes"
          exit 0
        else
          echo "Terraform plan succeeded with no changes"
        exit 0
        fi
      workingDirectory: $(TF_DIR)
      displayName: "Terraform Plan"

    # ----------------------------
    # 4. TERRAFORM APPLY (optional stage gating recommended)
    # ----------------------------
    - script: |
        terraform apply -auto-approve -var-file=pipeline.tfvars

      workingDirectory: $(System.DefaultWorkingDirectory)/infra-epicbook
      displayName: "Terraform Apply"