trigger:
- main

pool:
  name: epicbook-deploy-agent

variables:
- group: epicbook-secrets
- name: TF_IN_AUTOMATION
  value: true

stages:

- stage: TerraformDeploy
  displayName: "Terraform Deploy"

  jobs:
  - job: terraform
    displayName: "Terraform Job"

    steps:

    # -----------------------------
    # INIT
    # -----------------------------
    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'infra-epicbook'
        backendServiceArm: 'epicbook-devops-sb'
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'tfstatedobepicbook'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'epicbook.tfstate'

    # -----------------------------
    # VALIDATE
    # -----------------------------
    - task: TerraformTaskV4@4
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'infra-epicbook'

    # -----------------------------
    # LOAD SSH KEY (SECURE FILE)
    # -----------------------------
    - task: DownloadSecureFile@1
      name: sshkey
      inputs:
        secureFile: 'azure_vm_key.pub'
      displayName: "Download SSH Public Key"

    # Normalize SSH key into pipeline variable
    - bash: |
        KEY=$(cat $(sshkey.secureFilePath) | tr -d '\r' | tr -d '\n')
        echo "##vso[task.setvariable variable=ssh_public_key]$KEY"
      displayName: "Load SSH Key into Variable"

    # -----------------------------
    # PLAN
    # -----------------------------
    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'infra-epicbook'
        environmentServiceNameAzureRM: 'epicbook-devops-sb'
        commandOptions: >
          -var="ssh_public_key=$(ssh_public_key)"

    # -----------------------------
    # APPLY
    # -----------------------------
    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'infra-epicbook'
        environmentServiceNameAzureRM: 'epicbook-devops-sb'
        commandOptions: >
          -auto-approve
          -var="ssh_public_key=$(ssh_public_key)"

    # -----------------------------
    # OUTPUTS
    # -----------------------------
    - task: TerraformTaskV4@4
      displayName: "Terraform Output"
      inputs:
        provider: 'azurerm'
        command: 'output'
        workingDirectory: 'infra-epicbook'

    - script: |
        terraform output -json > tfoutputs.json
      workingDirectory: infra-epicbook
      displayName: "Export Terraform Outputs"

    - publish: infra-epicbook/tfoutputs.json
      artifact: tfoutputs
      displayName: "Publish Outputs"